### ISSUE TITLE
Geforce Now Unblocked

### ISSUE THREAD

**Issue by lunathenutgobbler** [nate-games/nate-games.github.io#28]
### Rating

7

### Game Name

Geforce Unblocked

### URL of the Game

https://www.play.geforcenow.com/

### Game Type

HTML5

### Comment

The one that you added is blocked for me and I wan't to play Fortnite but I can't.

**Comment by nate-games** [comment]
Updating now.... These changes take about 10 minutes, return to the same webpage **WITH** a proxy or VPN, click on GeForce...

Since its against GitHub's [TOS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service) I had to remove it and I cannot tell you exactly how to use a unblocker.

**Comment by nate-games** [comment]
If you don't know how to do it try using [Amazon Luna](https://nate-games.github.io/0/a/luna/) it is free as long as you have [Amazon Prime](https://www.amazon.com/amazonprime), there is also a 30-day free trial if you don't have it. I guarantee it is unblocked, it is just like GeForce NOW & Cloud Gaming.
